[package]
name = "libpwman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbkdf2 = "0.11.0"
aes-gcm = "0.10.1"
rand = "0.8.5"
generic-array = "0.14.6"
crc = "3.0.0"
# nom = "7.1.1"
